sonar.projectKey=django-admin-autocomplete-filter
sonar.projectName=django-admin-autocomplete-filter
sonar.projectVersion=1.0

sonar.sources=admin_auto_filters
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
