name: Test SonarQube

on:
  push:
    branches:
      - pre_release
      - dev
      - master

permissions:
  contents: read

jobs:
  sonarqube:
    name: Test SonarQube Scan
    runs-on: ${{ vars.AWS_RG_NAME_PRO }}
    if: ${{ github.ref_type == 'branch' && (github.ref_name == 'pre_release' || github.ref_name == 'dev' || github.ref_name == 'master') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: SonarQube Scan
        uses: aplazame/.github/workflows/test-reusable-sonarqube.yml@master
        env:
          SONAR_TOKEN: ${{ secrets.WZ_SONAR_TOKEN }}
