name: Test SonarQube

on:
  push:
    branches:
      - pre_release
      - dev
      - master
  pull_request:
    branches:
      - pre_release
      - dev
      - master

permissions:
  contents: read
  actions: read

jobs:
  sonarqube:
    name: Test SonarQube Scan
    uses: aplazame/.github/workflows/test-reusable-sonarqube.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.WZ_SONAR_TOKEN }}
